@startuml beta syntax

start
:create comment;
fork
    :add to dashboard;
fork again
    :add to thread;
end fork
:send email>
split
    :receive reply<
    label approve
    :Display Comment;
    stop

split again
    :decide on dashboard;
    if () then
        :approve;
        goto approve
    else
        :reject;
        label reject
        :Delete Comment;
        stop
    endif

split again
    :<&clock> 2 days;
    goto reject

end split

@enduml