@startuml
(*) --> "Create Comment"
--> ==CREATING==
==CREATING== --> "Add to Dashboard"
==CREATING== --> "Add to Thread"
"Add to Dashboard"-->==CREATED==
"Add to Thread"--> ==CREATED==
-->"Send Email"
if "" then
-->wait 2 days
-->"Delete Comment" as Delete
-->(*)
else
-->receive email
-->"Display Comment" as Display
-->(*)
else
-->decide on Dashboard
if ""
-->[Approve] Display
else
-->[Reject] Delete
endif
@enduml