@startuml sequenceDiagram

participant administrator
participant library
participant "each post" as eachPost
participant "pending comment" as pendingComment
actor approver

administrator->library
library->eachPost : get \npending \ncomments
eachPost->pendingComment : are you pending?
eachPost-->library : pending \ncomments

library->pendingComment : request \napproval
activate pendingComment #DarkBlue
approver-\pendingComment : approve
activate pendingComment
deactivate pendingComment

library<--pendingComment
deactivate pendingComment

library-->administrator

@enduml