@startuml
actor Moderator
actor Author
actor Reader
Moderator --> (Create Magazine)
Moderator --> (Approve a comment)
Author --> (Approve a comment)
Author --> (Create an article)
Author --> (by email)
Reader --> (Make a comment)
(Create an article) --|> (Create Magazine) : <<requires>>
(by email) --|> (Approve a comment) : << extends >>
(Approve a comment) --|> (Create an article) : <<requires>>
(Make a comment) --|> (Create an article) : <<requires>>
@enduml